/*******************************************************************************
 * Copyright (c) 2016 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.html
 *
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package org.eclipse.scout.contacts.events.shared.person.edu;

import javax.annotation.Generated;

import org.eclipse.scout.contacts.shared.person.PersonFormData;
import org.eclipse.scout.rt.platform.extension.Extends;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Extends(PersonFormData.class)
@Generated(value = "org.eclipse.scout.contacts.events.client.person.edu.EduPersonFormExtension", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class EduPersonFormExtensionData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public PoBox getPoBox() {
    return getFieldByClass(PoBox.class);
  }

  public static class PoBox extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
